{% set version = "2.9.2" %}

package:
  name: python-coveralls
  version: {{ version }}

source:
  fn: python-coveralls-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/python-coveralls/python-coveralls-{{ version }}.tar.gz
  sha256: 38a8c55849308b136f9b831e7ac972f9b6d0068d0087cd75dc147ac6a0e8e360

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - coveralls = coveralls:wear

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pyyaml
    - requests
    - coverage ==4.0.3
    - six

test:
  imports:
    - coveralls

  commands:
    - coveralls --help

about:
  home: http://github.com/z4r/python-coveralls
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Python interface to coveralls.io API\n'

extra:
  recipe-maintainers:
    - jakirkham
