{% set version = "2.9.1" %}

package:
  name: python-coveralls
  version: {{ version }}

source:
  fn: python-coveralls-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/python-coveralls/python-coveralls-{{ version }}.tar.gz
  sha256: 736dda01f64beda240e1500d5f264b969495b05fcb325c7c0eb7ebbfd1210b70

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - coveralls = coveralls:wear

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pyyaml
    - requests
    - coverage ==4.0.3
    - six

test:
  imports:
    - coveralls

  commands:
    - coveralls --help

about:
  home: http://github.com/z4r/python-coveralls
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Python interface to coveralls.io API\n'

extra:
  recipe-maintainers:
    - jakirkham
