{% set version = "2.9.3" %}

package:
  name: python-coveralls
  version: {{ version }}

source:
  fn: python-coveralls-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/python-coveralls/python-coveralls-{{ version }}.tar.gz
  sha256: bfaf7811e7dc5628e83b6b162962a4e2485dbff184b30e49f380374ed1bcee55

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - coveralls = coveralls:wear

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - pyyaml
    - requests
    - coverage
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - coveralls

  commands:
    - coveralls --help

about:
  home: http://github.com/z4r/python-coveralls
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Python interface to coveralls.io API\n'

extra:
  recipe-maintainers:
    - jakirkham
