travis:
  secure:
    BINSTAR_TOKEN: r1sQxfazpqgqaGogqDyR0MP2ff3INnjMUDRXZWj9SRQlQz16oUSGLa6sC+ClO2Xpl90Y9pIMHArKyggczscVbYFMaMK0x2XpVcw+qgrAIT7IdytoDPRZCanLE5jvxolr6tH+6JT8XngrIVWQgjgH5ggi0K7unu/LWc+/GlHTKYqoTOdu93nUuDknxVsmN/SLgOltMMs8f4lKbfmY7FDBvGNxYfgV+lzn4OYCvKRvWjzThSV+e6pHEULtnvrsAHB99idUk2QYhrDigXgLNwEX6p3x069ETNz2UCkygfsS3ltOv6tcpDtsgn53zHL2QTnVVImDAX8gcV7kgNTzFm7eg3XPCXDYYvV759uiqz16nXNjMiRuKFLfovz1DhIhXfkTKvUHLxsPWRyFqUSV1Wk2k0gvo6RlLC+ghTfvdlI0RhAaOCzd1uHmBgYv8r+0rfWWO3nJrZvcKHq+L54TxXeRUfTrQhFnHUJEacIhIyxMatGiBFb2rr9VS46go3oB7ZNNSODXscLTviFKYcuMNtpBLqq/dcKP/ZYrc8vpuCQMehSCQzm09pG3/9j7xSNLD3IG4T2yKb++ObVPT66iy5TRnfeOocfLmfDgXnQmuhB9ilM8iAGv9onkErRnx0R2nwli5TYuwJej33jTceHXIlscP8ezcKwluNeYv6EKcX/YXSg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
