travis:
  secure:
    BINSTAR_TOKEN: cpjkb/5JheXI6olM9T5u/PJsRz+QBJ7p1jjzw+vVX5wexClN8GrqmmdacwiBMaYc/BqLhgtAibuKgUgYU2t9YT7tMGD0iVUasu4L+nFuQLatZS02ZU+OZKf6N9AMt2e5dyIllLv62OQOS4vTxt9dIXe7UQzkn76gyqwoyB9cvLdSFgzahtKP12zI6XfygkO9WQq6M2gMXfczcH4HTnLqonEa0+MSJPAaAX/1EEdmPfflIgIhZJBBIVk0/TIaRKQG4n7RnZMij1BDdfqtqtTCrT9hIuJuG/2QHlgoHflJmW1uS/OO48tK+oWJ7s8ZbCGwwGyQrzwpp0IYyCJgdhAPMQ+CNEfzQLvgr2Ypvhuue2T2q00K02xhBaGOeVZyBWuiWmwsVFw3FogwNzzz/hBAxUCTXeofC8WbwjRvhoMnkhN39/tAxgLX4t7RZ8qrfDmDLnBr9Txc6YtGX6lkLtdv96KAxloEBa6GjcGVqr4j3zryOlWPs43rpu7ilFGlOko1ntDePfAxy8giRXRp1/V18GBg1EUYTpgIfHEnRx7CP9tPmUf2we0D0D+I1cV6ZMMlRWyBTKIUMMfmK6IWEre4dkQf4FX0zQpTBMVtD7QVh5mpU8hpHUJ5bfcMLDqSZrm7gSTQDBWs+NC0mfS2la9331WZeVegInZ0ZvfMqfl5zjw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
